id: https://example.com/BenefitSoilSampleMetadata
name: BenefitSoilSampleMetadata
title: BENEFIT Soil Sample Metadata
description: Metadata associated with the soil samples collected as part of the BENEFIT
  project.
version: 0.0.0
in_language: en
imports:
- linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
classes:
  BenefitSoilSampleMetadata:
    name: BenefitSoilSampleMetadata
    title: BENEFIT Soil Sample Metadata
    description: Metadata associated with the soil samples collected as part of the
      BENEFIT project.
    keywords: RDF106
    slots:
    - Activity_1.1
    - Activity_1.3
    - Activity_1.4
    - Activity_2.1
    - City
    - Collected
    - GCS_ID
    - Host_Plant
    - Latitude
    - Longitude
    - Notes
    - Original_soil_label
    - Province
    - Received
    - Soil_type
    - Storage
    slot_usage:
      Activity_1.1:
        rank: 1
        slot_group: General
      Activity_1.3:
        rank: 2
        slot_group: General
      Activity_1.4:
        rank: 3
        slot_group: General
      Activity_2.1:
        rank: 4
        slot_group: General
      City:
        rank: 5
        slot_group: General
      Collected:
        rank: 6
        slot_group: General
      GCS_ID:
        rank: 7
        slot_group: General
      Host_Plant:
        rank: 8
        slot_group: General
      Latitude:
        rank: 9
        slot_group: General
      Longitude:
        rank: 10
        slot_group: General
      Notes:
        rank: 11
        slot_group: General
      Original_soil_label:
        rank: 12
        slot_group: General
      Province:
        rank: 13
        slot_group: General
      Received:
        rank: 14
        slot_group: General
      Soil_type:
        rank: 15
        slot_group: General
      Storage:
        rank: 16
        slot_group: General
  Container:
    name: Container
    tree_root: true
    attributes:
      name: BenefitSoilSampleMetadataData
      multivalued: true
      range: BenefitSoilSampleMetadata
      inlined_as_list: true
slots:
  Activity_1.1:
    name: Activity_1.1
    title: Activity 1.1 soils
    description: An indication of whether the soil was used as part of Activity 1.1
      research
    recommended: true
    range: Boolean
  Activity_1.3:
    name: Activity_1.3
    title: Activity 1.3 soils
    description: An indication of whether the soil was used as part of Activity 1.3
      research
    recommended: true
    range: Boolean
  Activity_1.4:
    name: Activity_1.4
    title: Activity 1.4 soils
    description: An indication of whether the soil was used as part of Activity 1.4
      research
    recommended: true
    range: Boolean
  Activity_2.1:
    name: Activity_2.1
    title: Activity 2.1 soils
    description: An indication of whether the soil was used as part of Activity 2.1
      research
    recommended: true
    range: Boolean
  City:
    name: City
    title: City
    description: The city that the soil was collected from
    required: true
    range: WhitespaceMinimizedString
    pattern: ^.{0,250}$
  Collected:
    name: Collected
    title: Date of collection
    description: The date that the soil sample was collected
    recommended: true
    range: DateTime
    pattern: ^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$
  GCS_ID:
    name: GCS_ID
    title: Genome Canada Soil ID
    description: Unique numerical identifier of each soil sample
    required: true
    range: WhitespaceMinimizedString
    pattern: ^.{0,50}$
  Host_Plant:
    name: Host_Plant
    title: Associated plant species
    description: The plant species that was planted in the soil at the time of soil
      collection
    required: true
    range: WhitespaceMinimizedString
    pattern: ^.{0,250}$
  Latitude:
    name: Latitude
    title: Latitude
    description: The latitude of the soil collection site
    required: true
    range: decimal
    pattern: ^[-+]?\d*\.?\d+$
  Longitude:
    name: Longitude
    title: Longitude
    description: The longitude of the soil collection site
    required: true
    range: decimal
    pattern: ^[-+]?\d*\.?\d+$
  Notes:
    name: Notes
    title: Notes
    description: Additional notes relevant to the soil sample
    recommended: true
    range: WhitespaceMinimizedString
    pattern: ^.{0,4000}$
  Original_soil_label:
    name: Original_soil_label
    title: Original soil label
    description: Original name/label given to each soil during collection
    recommended: true
    range: WhitespaceMinimizedString
    pattern: ^.{0,250}$
  Province:
    name: Province
    title: Province
    description: The province that the soil was collected from
    required: true
    any_of:
    - range: WhitespaceMinimizedString
    - range: Province
    pattern: ^.{0,50}$
  Received:
    name: Received
    title: Date of receipt
    description: The date that the soil sample was received at the lab
    recommended: true
    range: DateTime
    pattern: ^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$
  Soil_type:
    name: Soil_type
    title: Soil type (bulk soil or rhizosphere)
    description: If specified, whether the soil sample represents bulk soil or rhizosphere
      soil
    recommended: true
    any_of:
    - range: WhitespaceMinimizedString
    - range: Soil_type
    pattern: ^.{0,50}$
  Storage:
    name: Storage
    title: Storage
    description: How the soil sample was stored
    recommended: true
    range: WhitespaceMinimizedString
    pattern: ^.{0,800}$
enums:
  SettingsMenu:
    name: SettingsMenu
    title: Regular Expressions
    permissible_values:
      AllCaps:
        title: AllCaps
        description: Entries of any length with only capital letters
      AlphaText1-50:
        title: AlphaText1-50
        description: Capital or lower case letters only, at least 1 character, and
          50 characters max
      AlphaText0-50:
        title: AlphaText0-50
        description: Capital or lower case letters only, 50 characters max
      FreeText0-50:
        title: FreeText0-50
        description: Short text, 50 characters max
      FreeText0-250:
        title: FreeText0-250
        description: Short text, 250 characters max
      FreeText0-800:
        title: FreeText0-800
        description: Long text, 800 characters max
      FreeText0-4000:
        title: FreeText0-4000
        description: Long text, 4000 characters max
      CanadianPostalCode:
        title: CanadianPostalCode
        description: Canadian postal codes (A1A 1A1)
      ZipCode:
        title: ZipCode
        description: USA Zip code
      EmailAddress:
        title: EmailAddress
        description: Email address
      URL:
        title: URL
        description: Secure (https) URL
      PhoneNumber:
        title: PhoneNumber
        description: Phone number with international and area code component.
      Latitude:
        title: Latitude
        description: "Latitude in formats S30\xB015'45.678\" or N12\xB030.999\""
      Longitude:
        title: Longitude
        description: "Longitude in formats E30\xB015'45.678\" or W90\xB000.000\""
      ISO_YYYY-MM-DD:
        title: ISO_YYYY-MM-DD
        description: year month day
      ISO_YYYYMMDD:
        title: ISO_YYYYMMDD
      ISO_YYYY-MM:
        title: ISO_YYYY-MM
        description: year month
      ISO_YYYY-Www:
        title: ISO_YYYY-Www
        description: year week (e.g. W01)
      ISO_YYYYWww:
        title: ISO_YYYYWww
        description: year week (e.g. W01)
      ISO_YYYY-DDD:
        title: ISO_YYYY-DDD
        description: Ordinal date (day number from the year)
      ISO_YYYYDDD:
        title: ISO_YYYYDDD
        description: Ordinal date (day number from the year)
      ISO_YYYY:
        title: ISO_YYYY
        description: year
      ISO_MM:
        title: ISO_MM
        description: month
      ISO_DD:
        title: ISO_DD
        description: day
      ISO_YYYY-MM-DDTHH.MM.SSZ:
        title: ISO_YYYY-MM-DDTHH:MM:SSZ
        description: Date and Time Combined (UTC)
      ISO_YYYY-MM-DDTHH.MM.SS-hh.mm:
        title: "ISO_YYYY-MM-DDTHH:MM:SS\xB1hh:mm"
        description: Date and Time Combined (with Timezone Offset)
      ISO_PnYnMnDTnHnMnS:
        title: ISO_PnYnMnDTnHnMnS
        description: durations e.g. P3Y6M4DT12H30M5S
      ISO_HH.MM:
        title: ISO_HH:MM
        description: hour, minutes in 24 hour notation
      ISO_HH.MM.SS:
        title: ISO_HH:MM:SS
        description: hour, minutes, seconds in 24 hour notation
      SLASH_DD_MM_YYYY:
        title: DD/MM/YYYY
        description: day, month, year
      SLASH_DD_MM_YY:
        title: DD/MM/YY
        description: day, month, year
      SLASH_MM_DD_YYYY:
        title: MM/DD/YYYY
        description: month, day, year
      DDMMYYYY:
        title: DDMMYYYY
        description: day, month, year
      MMDDYYYY:
        title: MMDDYYYY
        description: month, day, year
      YYYYMMDD:
        title: YYYYMMDD
        description: year, month, day
      HH.MM.SS:
        title: HH:MM:SS
        description: hour, minutes, seconds 12 hour notation AM/PM
      H.MM_or_HH.MM:
        title: H:MM or HH:MM
        description: hour, minutes AM/PM
  Province:
    name: Province
    title: Province
    permissible_values:
      AB:
        text: AB
        title: Alberta
      BC:
        text: BC
        title: British Columbia
      MB:
        text: MB
        title: Manitoba
      NB:
        text: NB
        title: New Brunswick
      NL:
        text: NL
        title: Newfoundland and Labrador
      NS:
        text: NS
        title: Nova Scotia
      NT:
        text: NT
        title: Northwest Territories
      NU:
        text: NU
        title: Nunavut
      'ON':
        text: 'ON'
        title: Ontario
      PE:
        text: PE
        title: Prince Edward Island
      QC:
        text: QC
        title: Quebec City
      SK:
        text: SK
        title: Saskatchewan
      YT:
        text: YT
        title: Yukon
  Soil_type:
    name: Soil_type
    title: Soil_type
    permissible_values:
      Bulk:
        text: Bulk
        title: Bulk soil
      Rhizosphere:
        text: Rhizosphere
        title: Rhizosphere soil
types:
  WhitespaceMinimizedString:
    name: WhitespaceMinimizedString
    typeof: string
    description: 'A string that has all whitespace trimmed off of beginning and end,
      and all internal whitespace segments reduced to single spaces. Whitespace includes
      x9 (tab), #xA (linefeed), and #xD (carriage return).'
    base: str
    uri: xsd:token
settings:
  Title_Case: ((?<=\b)[^a-z\W]\w*?|[\W])+
  UPPER_CASE: '[A-Z\W\d_]*'
  lower_case: '[a-z\W\d_]*'
  AllCaps: ^[A-Z]*$
  AlphaText1-50: ^[A-Za-z]{1,50}$
  AlphaText0-50: ^[A-Za-z]{0,50}$
  FreeText0-50: ^.{0,50}$
  FreeText0-250: ^.{0,250}$
  FreeText0-800: ^.{0,800}$
  FreeText0-4000: ^.{0,4000}$
  CanadianPostalCode: ^[A-Z][0-9][A-Z]\s[0-9][A-Z][0-9]$
  ZipCode: ^\d{5,6}(?:[-\s]\d{4})?$
  EmailAddress: ^[a-zA-Z0-9_\.\+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-\.]+
  URL: ^https?\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}$
  PhoneNumber: ^\+?\(?\d{2,4}\)?[\d\s-]{3,}$
  Latitude: "^[NS]-?(?:[0-8]?\\d|90)\xB0(?:\\d+(?:\\.\\d+)?)(?:'(\\d+(?:\\.\\d+)?)\"\
    )?$"
  Longitude: "^[WE]-?(?:[0-8]?\\d|90)\xB0(?:\\d+(?:\\.\\d+)?)(?:'(\\d+(?:\\.\\d+)?)\"\
    )?$"
  ISO_YYYY-MM-DD: ^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$
  ISO_YYYYMMDD: ^(\d{4})(0[1-9]|1[0-2])(0[1-9]|[1-2]\d|3[0-1])$
  ISO_YYYY-MM: ^(\d{4})-(0[1-9]|1[0-2])$
  ISO_YYYY-Www: ^(?:\d{4})-W(0[1-9]|[1-4][0-9]|5[0-3])$
  ISO_YYYYWww: ^(?:\d{4})W(0[1-9]|[1-4][0-9]|5[0-3])$
  ISO_YYYY-DDD: ^(?:\d{4})-(00[1-9]|0[1-9][0-9]|[1-2][0-9]{2}|3[0-5][0-9]|36[0-6])$
  ISO_YYYYDDD: ^(?:\d{4})(00[1-9]|0[1-9][0-9]|[1-2][0-9]{2}|3[0-5][0-9]|36[0-6])$
  ISO_YYYY: ^(\d{4})$
  ISO_MM: ^(0[1-9]|1[0-2])$
  ISO_DD: ^(0[1-9]|[1-2][0-9]|3[01])$
  ISO_YYYY-MM-DDTHH.MM.SSZ: ^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
  ISO_YYYY-MM-DDTHH.MM.SS-hh.mm: ^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\\d)([+-][01]\\d:[0-5]\d)$
  ISO_PnYnMnDTnHnMnS: ^P(?!$)((\d+Y)|(\d+.\d+Y)$)?((\d+M)|(\d+.\d+M)$)?((\d+W)|(\d+.\d+W)$)?((\d+D)|(\d+.\d+D)$)?(T(?=\d)((\d+H)|(\d+.\d+H)$)?((\d+M)|(\d+.\d+M)$)?(\d+(.\d+S)?)?)?$
  ISO_HH.MM: ^([01]\d|2[0-3]):([0-5]\d)$
  ISO_HH.MM.SS: ^([01]\d|2[0-3]):([0-5]\d):([0-5]\d)$
  SLASH_DD_MM_YYYY: ^(0[1-9]|[12]\d|3[01])/(0[1-9]|1[0-2])/\d{4}$
  SLASH_DD_MM_YY: ^(0[1-9]|[12]\d|3[01])/(0[1-9]|1[0-2])/\d{2}$
  SLASH_MM_DD_YYYY: ^(0[1-9]|1[0-2])/(0[1-9]|[12]\d|3[01])/\d{4}$
  DDMMYYYY: ^(0[1-9]|[12]\d|3[01])(0[1-9]|1[0-2])\d{4}$
  MMDDYYYY: ^(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])\d{4}$
  YYYYMMDD: ^(\d{4})(0[1-9]|1[0-2])(0[1-9]|[1-2]\d|3[0-1])$
  HH.MM.SS: ^(0?[1-9]|1[0-2]):[0-5][0-9]:[0-5][0-9] ?[APMapm]{2}$
  H.MM_or_HH.MM: ^(0?[1-9]|1[0-2]):[0-5][0-9] ?[APMapm]{2}$
