id: https://example.com/TeamActivateMultiGenusRotationalFieldTrial
name: TeamActivateMultiGenusRotationalFieldTrial
title: 'Team ACTIVATE: Multi-genus Rotational Field Trial'
description: This data schema refers to the Activity 2.3 phenotypic dataset which is taken on our large, multi-genus field trial.
version: 0.0.0
in_language: en
imports:
  - linkml:types
prefixes:
  linkml: https://w3id.org/linkml/
classes:
  TeamActivateMultiGenusRotationalFieldTrial:
    name: TeamActivateMultiGenusRotationalFieldTrial
    title: 'Team ACTIVATE: Multi-genus Rotational Field Trial'
    description: This data schema refers to the Activity 2.3 phenotypic dataset which is taken on our large, multi-genus field trial.
    keywords: RDF401
    slots:
      - Block
      - BlockCol
      - BlockRow
      - Col
      - Combo
      - Comment
      - Days_to_Emergence
      - Emergence_Date
      - Expt
      - Flowering_Date_R1
      - Half_Pods_Mature_R7
      - Lentil
      - Lodging
      - Maturity_Date_R7
      - NIR
      - NIR_LenPro_preTweak
      - Name
      - One_Open_Flower_R1
      - Planting_Date
      - Rep
      - Row
      - Type
      - UniqueID
      - Wheat
      - plot
      - yield_plot
      - yield_subsample
      - yield_total
    slot_usage:
      Block:
        name: Block
        rank: 1
        slot_group: General
      BlockCol:
        name: BlockCol
        rank: 2
        slot_group: General
      BlockRow:
        name: BlockRow
        rank: 3
        slot_group: General
      Col:
        name: Col
        rank: 4
        slot_group: General
      Combo:
        name: Combo
        rank: 5
        slot_group: General
      Comment:
        name: Comment
        rank: 6
        slot_group: General
      Days_to_Emergence:
        name: Days_to_Emergence
        rank: 7
        slot_group: General
      Emergence_Date:
        name: Emergence_Date
        rank: 8
        slot_group: General
      Expt:
        name: Expt
        rank: 9
        slot_group: General
      Flowering_Date_R1:
        name: Flowering_Date_R1
        rank: 10
        slot_group: General
      Half_Pods_Mature_R7:
        name: Half_Pods_Mature_R7
        rank: 11
        slot_group: General
      Lentil:
        name: Lentil
        rank: 12
        slot_group: General
      Lodging:
        name: Lodging
        rank: 13
        slot_group: General
      Maturity_Date_R7:
        name: Maturity_Date_R7
        rank: 14
        slot_group: General
      NIR:
        name: NIR
        rank: 15
        slot_group: General
      NIR_LenPro_preTweak:
        name: NIR_LenPro_preTweak
        rank: 16
        slot_group: General
      Name:
        name: Name
        rank: 17
        slot_group: General
      One_Open_Flower_R1:
        name: One_Open_Flower_R1
        rank: 18
        slot_group: General
      Planting_Date:
        name: Planting_Date
        rank: 19
        slot_group: General
      Rep:
        name: Rep
        rank: 20
        slot_group: General
      Row:
        name: Row
        rank: 21
        slot_group: General
      Type:
        name: Type
        rank: 22
        slot_group: General
      UniqueID:
        name: UniqueID
        rank: 23
        slot_group: General
      Wheat:
        name: Wheat
        rank: 24
        slot_group: General
      plot:
        name: plot
        rank: 25
        slot_group: General
      yield_plot:
        name: yield_plot
        rank: 26
        slot_group: General
      yield_subsample:
        name: yield_subsample
        rank: 27
        slot_group: General
      yield_total:
        name: yield_total
        rank: 28
        slot_group: General
  Container:
    name: Container
    tree_root: true
    attributes:
      name: TeamActivateMultiGenusRotationalFieldTrialData
      multivalued: true
      range: TeamActivateMultiGenusRotationalFieldTrial
      inlined_as_list: true
slots:
  Block:
    name: Block
    title: Block
    range: decimal
    required: true
    description: Block number
  BlockCol:
    name: BlockCol
    title: BlockCol
    range: decimal
    required: true
    description: Column number within block
  BlockRow:
    name: BlockRow
    title: BlockRow
    range: decimal
    required: true
    description: Row number within block
  Col:
    name: Col
    title: Col
    range: decimal
    required: true
    description: Column number
  Combo:
    name: Combo
    title: Combo
    range: WhitespaceMinimizedString
    required: true
    description: Identifies the Lentil-Wheat combination evaluated in this plot.
  Comment:
    name: Comment
    title: Comment
    range: WhitespaceMinimizedString
    recommended: true
    description: General comments from the field crew that may be pertinent to know during analysis.
  Days_to_Emergence:
    name: Days_to_Emergence
    title: Days to Emergence (date)
    range: decimal
    unit:
      ucum_code: days
    recommended: true
    description: The number of days from the date of planting to the \"Emergence Date\".
  Emergence_Date:
    name: Emergence_Date
    title: Emergence Date (date)
    range: DateTime
    unit:
      ucum_code: year-month-day
    recommended: true
    description: The date on which at least 50% of the seeds within the plot are visible above the soil.
  Expt:
    name: Expt
    title: Expt
    any_of:
      - range: WhitespaceMinimizedString
      - range: Expt
    required: true
    description: Captures the particular siteyear and Lentil/Wheat portion of the experiment evaluated in this row. This also indicates where and then these data were collected.
  Flowering_Date_R1:
    name: Flowering_Date_R1
    title: Flowering Date (R1; date)
    range: DateTime
    unit:
      ucum_code: year-month-day
    recommended: true
    description: The date at which there is one open flower at any node on 50% of the plants in the plot. This is R1 in the Lentil Reproductive & Maturity Staging Guide.
  Half_Pods_Mature_R7:
    name: Half_Pods_Mature_R7
    title: Days till 10% of Plants have 1/2 Pods Mature (R7; days)
    range: decimal
    unit:
      ucum_code: days
    recommended: true
    description: The number of days from the date of planting to the \"Maturity Date\" where the Maturity date is the date the plants reach R7 according to the Lentil Reproductive & Maturity Staging Guide.
  Lentil:
    name: Lentil
    title: Lentil
    range: WhitespaceMinimizedString
    required: true
    description: Uniquely identifies the Lentil germplasm planted in this plot within the trial.
  Lodging:
    name: Lodging
    title: Lodging (scale; 1=upright; 5=prostrate)
    any_of:
      - range: decimal
      - range: Lodging
    unit:
      ucum_code: scale
    recommended: true
    description: Indicates the rate of lodging in the plot between R6-R7 where lodging is defined as an irreversible falling over of the primary plant stem greater than 45 degrees.
  Maturity_Date_R7:
    name: Maturity_Date_R7
    title: Maturity Date (R7; date)
    range: DateTime
    unit:
      ucum_code: year-month-day
    recommended: true
    description: This is R7 in the Lentil Reproductive & Maturity Staging Guide.
  NIR:
    name: NIR
    title: NIR
    range: decimal
    unit:
      ucum_code: percent protein
    recommended: true
    description: Protein percentage estimated by Near Infrared Spectroscopy (updated calibration)
  NIR_LenPro_preTweak:
    name: NIR_LenPro_preTweak
    title: NIR_LenPro_preTweak
    range: decimal
    unit:
      ucum_code: percent protein
    recommended: true
    description: Protein percentage estimated by Near Infrared Spectroscopy (old calibration)
  Name:
    name: Name
    title: Name
    range: WhitespaceMinimizedString
    required: true
    description: The full name of the Lentil or Wheat germplasm evaluated in this particular row.
  One_Open_Flower_R1:
    name: One_Open_Flower_R1
    title: Days till 10% of Plants have One Open Flower (R1; days)
    range: decimal
    unit:
      ucum_code: days
    recommended: true
    description: The number of days from the date of planting to the \"Flowering Date\" where the Flowering date is the date the plants reach R1 according to the Lentil Reproductive & Maturity Staging Guide.
  Planting_Date:
    name: Planting_Date
    title: Planting Date (date)
    range: DateTime
    unit:
      ucum_code: year-month-day
    recommended: true
    description: The date the seeds were sown.
  Rep:
    name: Rep
    title: Rep
    range: WhitespaceMinimizedString
    required: true
    description: Replication number
  Row:
    name: Row
    title: Row
    range: decimal
    required: true
    description: Row number
  Type:
    name: Type
    title: Type
    any_of:
      - range: WhitespaceMinimizedString
      - range: Type
    required: true
    description: Treatment or check
  UniqueID:
    name: UniqueID
    title: Unique ID
    range: WhitespaceMinimizedString
    required: true
    description: Uniquely identifies the particular plot within the larger trial. It consists of the year the plot was grown, the Plot ID and either the Lentil OR Wheat ID depending on which is grown when these data are taken.
  Wheat:
    name: Wheat
    title: Wheat
    range: WhitespaceMinimizedString
    required: true
    description: Uniquely identifies the Wheat germplasm planted in this plot within the trial.
  plot:
    name: plot
    title: Plot
    range: WhitespaceMinimizedString
    required: true
    description: Identifies the plot uniquely within a given location/year (i.e. siteyear).
  yield_plot:
    name: yield_plot
    title: yield plot (g)
    range: decimal
    unit:
      ucum_code: grams
    recommended: true
    description: The weight of the seed harvested from the plot by the combine.
  yield_subsample:
    name: yield_subsample
    title: yield subsample (g)
    range: decimal
    unit:
      ucum_code: grams
    recommended: true
    description: Some plots have yield subsampled at R7 by hand. This value is recorded here.
  yield_total:
    name: yield_total
    title: yield total (g)
    range: decimal
    unit:
      ucum_code: grams
    recommended: true
    description: For subsampled plots this is the yield from both the combine and the subsample. For others this will be equal to the plot yield measurement.
enums:
  SettingsMenu:
    name: SettingsMenu
    title: Regular Expressions
    permissible_values:
      AllCaps:
        title: AllCaps
        description: Entries of any length with only capital letters
      AlphaText1-50:
        title: AlphaText1-50
        description: Capital or lower case letters only, at least 1 character, and 50 characters max
      AlphaText0-50:
        title: AlphaText0-50
        description: Capital or lower case letters only, 50 characters max
      FreeText0-50:
        title: FreeText0-50
        description: Short text, 50 characters max
      FreeText0-250:
        title: FreeText0-250
        description: Short text, 250 characters max
      FreeText0-800:
        title: FreeText0-800
        description: Long text, 800 characters max
      FreeText0-4000:
        title: FreeText0-4000
        description: Long text, 4000 characters max
      CanadianPostalCode:
        title: CanadianPostalCode
        description: Canadian postal codes (A1A 1A1)
      ZipCode:
        title: ZipCode
        description: USA Zip code
      EmailAddress:
        title: EmailAddress
        description: Email address
      URL:
        title: URL
        description: Secure (https) URL
      PhoneNumber:
        title: PhoneNumber
        description: Phone number with international and area code component.
      Latitude:
        title: Latitude
        description: Latitude in formats S30°15'45.678" or N12°30.999"
      Longitude:
        title: Longitude
        description: Longitude in formats E30°15'45.678" or W90°00.000"
      ISO_YYYY-MM-DD:
        title: ISO_YYYY-MM-DD
        description: year month day
      ISO_YYYYMMDD:
        title: ISO_YYYYMMDD
      ISO_YYYY-MM:
        title: ISO_YYYY-MM
        description: year month
      ISO_YYYY-Www:
        title: ISO_YYYY-Www
        description: year week (e.g. W01)
      ISO_YYYYWww:
        title: ISO_YYYYWww
        description: year week (e.g. W01)
      ISO_YYYY-DDD:
        title: ISO_YYYY-DDD
        description: Ordinal date (day number from the year)
      ISO_YYYYDDD:
        title: ISO_YYYYDDD
        description: Ordinal date (day number from the year)
      ISO_YYYY:
        title: ISO_YYYY
        description: year
      ISO_MM:
        title: ISO_MM
        description: month
      ISO_DD:
        title: ISO_DD
        description: day
      ISO_YYYY-MM-DDTHH.MM.SSZ:
        title: ISO_YYYY-MM-DDTHH:MM:SSZ
        description: Date and Time Combined (UTC)
      ISO_YYYY-MM-DDTHH.MM.SS-hh.mm:
        title: ISO_YYYY-MM-DDTHH:MM:SS±hh:mm
        description: Date and Time Combined (with Timezone Offset)
      ISO_PnYnMnDTnHnMnS:
        title: ISO_PnYnMnDTnHnMnS
        description: durations e.g. P3Y6M4DT12H30M5S
      ISO_HH.MM:
        title: ISO_HH:MM
        description: hour, minutes in 24 hour notation
      ISO_HH.MM.SS:
        title: ISO_HH:MM:SS
        description: hour, minutes, seconds in 24 hour notation
      SLASH_DD_MM_YYYY:
        title: DD/MM/YYYY
        description: day, month, year
      SLASH_DD_MM_YY:
        title: DD/MM/YY
        description: day, month, year
      SLASH_MM_DD_YYYY:
        title: MM/DD/YYYY
        description: month, day, year
      DDMMYYYY:
        title: DDMMYYYY
        description: day, month, year
      MMDDYYYY:
        title: MMDDYYYY
        description: month, day, year
      YYYYMMDD:
        title: YYYYMMDD
        description: year, month, day
      HH.MM.SS:
        title: HH:MM:SS
        description: hour, minutes, seconds 12 hour notation AM/PM
      H.MM_or_HH.MM:
        title: H:MM or HH:MM
        description: hour, minutes AM/PM
  Expt:
    name: Expt
    title: Expt
    permissible_values:
      ACTIVATE 2024 Clavet Lentil:
        text: ACTIVATE 2024 Clavet Lentil
        title: ACTIVATE 2024 Clavet Lentil
      ACTIVATE 2024 Hunter Lentil:
        text: ACTIVATE 2024 Hunter Lentil
        title: ACTIVATE 2024 Hunter Lentil
      ACTIVATE 2025 Clavet Wheat:
        text: ACTIVATE 2025 Clavet Wheat
        title: ACTIVATE 2025 Clavet Wheat
      ACTIVATE 2025 Hunter Wheat:
        text: ACTIVATE 2025 Hunter Wheat
        title: ACTIVATE 2025 Hunter Wheat
  Lodging:
    name: Lodging
    title: Lodging
    permissible_values:
      '1':
        text: '1'
        title: Upright
      '5':
        text: '5'
        title: Prostate
  Type:
    name: Type
    title: Type
    permissible_values:
      Check:
        text: Check
        title: Check
      Treatment:
        text: Treatment
        title: Treatment
types:
  WhitespaceMinimizedString:
    name: WhitespaceMinimizedString
    typeof: string
    description: 'A string that has all whitespace trimmed off of beginning and end, and all internal whitespace segments reduced to single spaces. Whitespace includes x9 (tab), #xA (linefeed), and #xD (carriage return).'
    base: str
    uri: xsd:token
settings:
  Title_Case: ((?<=\b)[^a-z\W]\w*?|[\W])+
  UPPER_CASE: '[A-Z\W\d_]*'
  lower_case: '[a-z\W\d_]*'
  AllCaps: ^[A-Z]*$
  AlphaText1-50: ^[A-Za-z]{1,50}$
  AlphaText0-50: ^[A-Za-z]{0,50}$
  FreeText0-50: ^.{0,50}$
  FreeText0-250: ^.{0,250}$
  FreeText0-800: ^.{0,800}$
  FreeText0-4000: ^.{0,4000}$
  CanadianPostalCode: ^[A-Z][0-9][A-Z]\s[0-9][A-Z][0-9]$
  ZipCode: ^\d{5,6}(?:[-\s]\d{4})?$
  EmailAddress: ^[a-zA-Z0-9_\.\+-]+@[a-zA-Z0-9-]+\.[a-zA-Z0-9-\.]+
  URL: ^https?\:\/\/[a-zA-Z0-9\-\.]+\.[a-zA-Z]{2,}$
  PhoneNumber: ^\+?\(?\d{2,4}\)?[\d\s-]{3,}$
  Latitude: ^[NS]-?(?:[0-8]?\d|90)°(?:\d+(?:\.\d+)?)(?:'(\d+(?:\.\d+)?)")?$
  Longitude: ^[WE]-?(?:[0-8]?\d|90)°(?:\d+(?:\.\d+)?)(?:'(\d+(?:\.\d+)?)")?$
  ISO_YYYY-MM-DD: ^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])$
  ISO_YYYYMMDD: ^(\d{4})(0[1-9]|1[0-2])(0[1-9]|[1-2]\d|3[0-1])$
  ISO_YYYY-MM: ^(\d{4})-(0[1-9]|1[0-2])$
  ISO_YYYY-Www: ^(?:\d{4})-W(0[1-9]|[1-4][0-9]|5[0-3])$
  ISO_YYYYWww: ^(?:\d{4})W(0[1-9]|[1-4][0-9]|5[0-3])$
  ISO_YYYY-DDD: ^(?:\d{4})-(00[1-9]|0[1-9][0-9]|[1-2][0-9]{2}|3[0-5][0-9]|36[0-6])$
  ISO_YYYYDDD: ^(?:\d{4})(00[1-9]|0[1-9][0-9]|[1-2][0-9]{2}|3[0-5][0-9]|36[0-6])$
  ISO_YYYY: ^(\d{4})$
  ISO_MM: ^(0[1-9]|1[0-2])$
  ISO_DD: ^(0[1-9]|[1-2][0-9]|3[01])$
  ISO_YYYY-MM-DDTHH.MM.SSZ: ^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\d)Z$
  ISO_YYYY-MM-DDTHH.MM.SS-hh.mm: ^(\d{4})-(0[1-9]|1[0-2])-(0[1-9]|[12]\d|3[01])T([01]\d|2[0-3]):([0-5]\d):([0-5]\\d)([+-][01]\\d:[0-5]\d)$
  ISO_PnYnMnDTnHnMnS: ^P(?!$)((\d+Y)|(\d+.\d+Y)$)?((\d+M)|(\d+.\d+M)$)?((\d+W)|(\d+.\d+W)$)?((\d+D)|(\d+.\d+D)$)?(T(?=\d)((\d+H)|(\d+.\d+H)$)?((\d+M)|(\d+.\d+M)$)?(\d+(.\d+S)?)?)?$
  ISO_HH.MM: ^([01]\d|2[0-3]):([0-5]\d)$
  ISO_HH.MM.SS: ^([01]\d|2[0-3]):([0-5]\d):([0-5]\d)$
  SLASH_DD_MM_YYYY: ^(0[1-9]|[12]\d|3[01])/(0[1-9]|1[0-2])/\d{4}$
  SLASH_DD_MM_YY: ^(0[1-9]|[12]\d|3[01])/(0[1-9]|1[0-2])/\d{2}$
  SLASH_MM_DD_YYYY: ^(0[1-9]|1[0-2])/(0[1-9]|[12]\d|3[01])/\d{4}$
  DDMMYYYY: ^(0[1-9]|[12]\d|3[01])(0[1-9]|1[0-2])\d{4}$
  MMDDYYYY: ^(0[1-9]|1[0-2])(0[1-9]|[12]\d|3[01])\d{4}$
  YYYYMMDD: ^(\d{4})(0[1-9]|1[0-2])(0[1-9]|[1-2]\d|3[0-1])$
  HH.MM.SS: ^(0?[1-9]|1[0-2]):[0-5][0-9]:[0-5][0-9] ?[APMapm]{2}$
  H.MM_or_HH.MM: ^(0?[1-9]|1[0-2]):[0-5][0-9] ?[APMapm]{2}$
